import enum


class AddOnMovement(enum.Enum):
    BARRACKS_LEAVE_REACTOR = 0
    BARRACKS_LEAVE_TECHLAB = 1
    BARRACKS_LAND_REACTOR = 2
    BARRACKS_LAND_TECHLAB = 3
    BARRACKS_LIFT_EMPTY = 4
    BARRACKS_LAND_EMPTY = 5

    FACTORY_LEAVE_REACTOR = 6
    FACTORY_LEAVE_TECHLAB = 7
    FACTORY_LAND_REACTOR = 8
    FACTORY_LAND_TECHLAB = 9
    FACTORY_LIFT_EMPTY = 10
    FACTORY_LAND_EMPTY = 11

    STARPORT_LEAVE_REACTOR = 12
    STARPORT_LEAVE_TECHLAB = 13
    STARPORT_LAND_REACTOR = 14
    STARPORT_LAND_TECHLAB = 15
    STARPORT_LIFT_EMPTY = 16
    STARPORT_LAND_EMPTY = 17
